apply plugin: 'com.android.library'

Properties properties = new Properties()
properties.load(project.rootProject.file("gradle.properties").newDataInputStream())
def $sdk = properties.getProperty("sdk") as Integer
def $minSdkVersion = properties.getProperty("minSdkVersion") as Integer
def $javaVersion = properties.getProperty("javaVersion")

android {
    compileSdkVersion $sdk
    namespace 'com.github.johnpersano.supertoasts'

    defaultConfig {
        minSdk $minSdkVersion
        targetSdk $sdk
        compileOptions {
            sourceCompatibility JavaVersion.toVersion($javaVersion)
            targetCompatibility JavaVersion.toVersion($javaVersion)
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
